// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr_N8c4G3wz41uxUvFH1WW7kbuKGdP2Xk',
    appId: '1:784903071503:web:bbca698be4da144037007a',
    messagingSenderId: '784903071503',
    projectId: 'diesel-air-408507',
    authDomain: 'diesel-air-408507.firebaseapp.com',
    storageBucket: 'diesel-air-408507.appspot.com',
    measurementId: 'G-PRP0W71PZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypnSl6hE1NywWN180hQK0Rs4Ibejk4DU',
    appId: '1:784903071503:android:9e1bcb43c580e4ce37007a',
    messagingSenderId: '784903071503',
    projectId: 'diesel-air-408507',
    storageBucket: 'diesel-air-408507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1po-M0ETWXzpi37wZ92MJYD4W2wLEcc',
    appId: '1:784903071503:ios:8cb87a0af8114d7937007a',
    messagingSenderId: '784903071503',
    projectId: 'diesel-air-408507',
    storageBucket: 'diesel-air-408507.appspot.com',
    iosBundleId: 'com.example.parkingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR1po-M0ETWXzpi37wZ92MJYD4W2wLEcc',
    appId: '1:784903071503:ios:c87850b76957b13637007a',
    messagingSenderId: '784903071503',
    projectId: 'diesel-air-408507',
    storageBucket: 'diesel-air-408507.appspot.com',
    iosBundleId: 'com.example.parkingo.RunnerTests',
  );
}
