// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi5DxJ9OTZLUEFzo83vem8xvZhL62xbtU',
    appId: '1:208907000783:web:fa611036a0f2e6c54390ba',
    messagingSenderId: '208907000783',
    projectId: 'parkingo-de62c',
    authDomain: 'parkingo-de62c.firebaseapp.com',
    storageBucket: 'parkingo-de62c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwy6-uDhh3yScWc69-9l0XJhLtZWnYWPY',
    appId: '1:208907000783:android:053a6fcf1ab5fd444390ba',
    messagingSenderId: '208907000783',
    projectId: 'parkingo-de62c',
    storageBucket: 'parkingo-de62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDSrs6vtcS40SanWuy2qiPgTOLWv1QEk',
    appId: '1:208907000783:ios:289f99eee65a917c4390ba',
    messagingSenderId: '208907000783',
    projectId: 'parkingo-de62c',
    storageBucket: 'parkingo-de62c.appspot.com',
    iosBundleId: 'com.example.parkingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDSrs6vtcS40SanWuy2qiPgTOLWv1QEk',
    appId: '1:208907000783:ios:c20272bb8e19c02e4390ba',
    messagingSenderId: '208907000783',
    projectId: 'parkingo-de62c',
    storageBucket: 'parkingo-de62c.appspot.com',
    iosBundleId: 'com.example.parkingo.RunnerTests',
  );
}
